In [26]:
def isPrime(n):
    # Write your code here
    result = 0
    divisible_lst = []
    for i in range(2, (n//2) +1):
        if (n % i == 0):
            result +=1
            divisible_lst.append(i)
    answer = 0
    if result == 0:
        answer = 1
    else:
        divisible_lst.sort()
        answer = divisible_lst[0]
    return answer

In [29]:
isPrime(1072843847)

16141

In [28]:
4 //2

2

1

In [3]:
import numpy as np
dataset = [['Calculator', 100, 1000], 
            ['music player', 500, 3000], 
            ['Visual Novel', 1500, 5000], 
            ['Console', 3500, 8000], 
            ['2D Vector Art', 5000, 6500], 
            ['XBox', 6000, 7000], 
            ['PS', 8000, 15000], 
            ['Simulator', 9500, 20000], 
            ['Mobile', 12000, 21000], 
            ['RPG', 14000, 25000], 
            ['Monitor', 15500, 27000], 
            ['Tablet', 16500, 30000], 
            ['Laptop', 25000, 52000], 
            ['MMORPG', 30000, 80000]]
#write your Logic here: 
x = np.array(dataset)

In [5]:
x.shape

(14, 3)

In [17]:
import numpy as np   
import pandas as pd 
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
#INPUT [uncomment & modify if required] 
result=-404
dataset = [['Calculator', 100, 1000], 
            ['music player', 500, 3000], 
            ['Visual Novel', 1500, 5000], 
            ['Console', 3500, 8000], 
            ['2D Vector Art', 5000, 6500], 
            ['XBox', 6000, 7000], 
            ['PS', 8000, 15000], 
            ['Simulator', 9500, 20000], 
            ['Mobile', 12000, 21000], 
            ['RPG', 14000, 25000], 
            ['Monitor', 15500, 27000], 
            ['Tablet', 16500, 30000], 
            ['Laptop', 25000, 52000], 
            ['MMORPG', 30000, 80000]]
#write your Logic here: 

# Dummy encode the categorical values
data = pd.DataFrame(dataset, columns=["Name", "production_cost", "sales_price"])
final_data = pd.get_dummies(data)

# Extract the features and the the target variable
all_features = final_data.drop(["sales_price"], axis=1)
target = final_data.pop("sales_price")

# Split the data into train and test set (80% train, 20 test set)
train_x, test_x, train_y, test_y = train_test_split(all_features, target, test_size =0.2, random_state=2021)

# fit the CLF on the training set, and then test on the test set. 
classifier = DecisionTreeRegressor()
classifier.fit(train_x, train_y)
print(classifier.score(test_x, test_y))

#OUTPUT [uncomment & modify if required] 
name = input()
prod_cost = int(input())
print(result)

0.8839445438282647
"Laptop"
25000
-404

In [32]:
all_features

,production_cost,Name_2D Vector Art,Name_Calculator,Name_Console,Name_Laptop,Name_MMORPG,Name_Mobile,Name_Monitor,Name_PS,Name_RPG,Name_Simulator,Name_Tablet,Name_Visual Novel,Name_XBox,Name_music player
0,100,0,1,0,0,0,0,0,0,0,0,0,0,0,0
1,500,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,1500,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,3500,0,0,1,0,0,0,0,0,0,0,0,0,0,0
4,5000,1,0,0,0,0,0,0,0,0,0,0,0,0,0
5,6000,0,0,0,0,0,0,0,0,0,0,0,0,1,0
6,8000,0,0,0,0,0,0,0,1,0,0,0,0,0,0
7,9500,0,0,0,0,0,0,0,0,0,1,0,0,0,0
8,12000,0,0,0,0,0,1,0,0,0,0,0,0,0,0
9,14000,0,0,0,0,0,0,0,0,1,0,0,0,0,0
10,15500,0,0,0,0,0,0,1,0,0,0,0,0,0,0
11,16500,0,0,0,0,0,0,0,0,0,0,1,0,0,0
12,25000,0,0,0,1,0,0,0,0,0,0,0,0,0,0
13,30000,0,0,0,0,1,0,0,0,0,0,0,0,0,0

In [31]:
cols = list(all_features.columns)
production_cost 	Name_2D Vector Art 	Name_Calculator 	Name_Console 	Name_Laptop 	Name_MMORPG 	Name_Mobile 	Name_Monitor 	Name_PS 	Name_RPG 	Name_Simulator 	Name_Tablet 	Name_Visual Novel 	Name_XBox 	Name_music player

Index(['production_cost', 'Name_2D Vector Art', 'Name_Calculator',
       'Name_Console', 'Name_Laptop', 'Name_MMORPG', 'Name_Mobile',
       'Name_Monitor', 'Name_PS', 'Name_RPG', 'Name_Simulator', 'Name_Tablet',
       'Name_Visual Novel', 'Name_XBox', 'Name_music player'],
      dtype='object')

In [26]:
#OUTPUT [uncomment & modify if required] 
# Hi team, struggling a bit here...
# Should I not convert the new valued data to dummy encoding? :/ hmm.. 
# Would love to learn and hear your thoughts on why or why not. 
name = input()
prod_cost = int(input())
new_data = [[name,prod_cost]]
new_data = pd.DataFrame(new_data)
new_data = pd.get_dummies(new_data)

# Fixing the error -- Need same number of columns in input than in OUTPUT
# Extract the column headers from all_features. 
all_features.columns()


result = classifier.predict(new_data)
print(result)

"Laptop"
1000

TypeError: 'Index' object is not callable

In [13]:
# Dummy encode the categorical values
dataset2 = pd.DataFrame(dataset, columns = ["Name", "prod", "sale_price"])
#pd.get_dummies(dataset2)
dataset2

             Name   prod  sale_price
0      Calculator    100        1000
1    music player    500        3000
2    Visual Novel   1500        5000
3         Console   3500        8000
4   2D Vector Art   5000        6500
5            XBox   6000        7000
6              PS   8000       15000
7       Simulator   9500       20000
8          Mobile  12000       21000
9             RPG  14000       25000
10        Monitor  15500       27000
11         Tablet  16500       30000
12         Laptop  25000       52000
13         MMORPG  30000       80000

In [7]:
import numpy as np   
import pandas as pd 
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
#INPUT [uncomment & modify if required] 
result=-404
dataset = [['Calculator', 100, 1000], 
            ['music player', 500, 3000], 
            ['Visual Novel', 1500, 5000], 
            ['Console', 3500, 8000], 
            ['2D Vector Art', 5000, 6500], 
            ['XBox', 6000, 7000], 
            ['PS', 8000, 15000], 
            ['Simulator', 9500, 20000], 
            ['Mobile', 12000, 21000], 
            ['RPG', 14000, 25000], 
            ['Monitor', 15500, 27000], 
            ['Tablet', 16500, 30000], 
            ['Laptop', 25000, 52000], 
            ['MMORPG', 30000, 80000]]
#write your Logic here: 

# Split the data into train and test set (80% train, 20 test set)
data = np.array(dataset)
data.shape # 14,3
# Extract the features, X and the target variable
all_features = data[:, :2]
target = data[:, -1]
train_x, test_x, train_y, test_y = train_test_split(all_features, target, test_size =0.2, random_state=2021)

# fit the CLF on the training set, and then test on the test set. 
classifier = DecisionTreeRegressor()
classifier.fit(train_x, train_y)
print(classifer.score(test_x, test_y))

#OUTPUT [uncomment & modify if required] 
name = input()
prod_cost = int(input())
print(result)

ValueError: could not convert string to float: 'Simulator'